### ISSUE TITLE
Backup .dmg, help docs & APIs from the way back machine. 

### ISSUE THREAD

**Issue by nehemiahjacob** [vicoapp/vico#90]
It's sad that the maintainer decided to discontinue the site vicoapp.com
However, the content must be stored somewhere, possibly in this repo under docs folder. 
The last known best snapshot by the way back machine happened on Nov 2016 under this link

https://web.archive.org/web/20161118232250/http://www.vicoapp.com/

 - [x] Add last DMG to GitHub
 - [x] Import HTML docs from vicoapp.com
 - [ ] Import last two HTML files (`open_line.html` and `tagstack.html`) from vicoapp.com

**Comment by Shadowfiend** [comment]
Bummer. That's the original maintainer, who has long since stopped maintaining Vico. I'm the current one ish, though I haven't really had any time to devote to it in more than two years, unfortunately.

I would welcome some PRs to pull this stuff into a `docs` directory, and I'll see if I can put the DMG file up for download.

**Comment by Shadowfiend** [comment]
I've posted the historical DMG under a historical release @ https://github.com/vicoapp/vico/releases/tag/1.3.3 .

**Comment by Shadowfiend** [comment]
#91 added the help pages as HTML, but it sounds like we're missing `open_line.html` and `tagstack.html`, if anyone can dig that up. Thanks @andrewschleifer !

**Comment by nehemiahjacob** [comment]
Added a PR #92 it has full CSS and anchors are working fine, And it covers help pages and API docs.

**Comment by nehemiahjacob** [comment]
@Shadowfiend

**Comment by Shadowfiend** [comment]
Missed this; thanks for closing!
